# Generated by Django 5.2.8 on 2025-11-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="original_images/")),
                (
                    "translated_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="translated_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text_original", models.TextField(blank=True, null=True)),
                ("text_translated", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
