# Generated by Django 5.2.8 on 2025-11-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="is_translated",
            field=models.BooleanField(default=False),
        ),
    ]
